// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaPoshtaParalle;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaPoshtaParalle.Migrations
{
    [DbContext(typeof(MyApplicationContext))]
    [Migration("20250417141138_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaPoshtaParalle.Entities.Area", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ref");

                    b.ToTable("tblAreas");
                });

            modelBuilder.Entity("NovaPoshtaParalle.Entities.City", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "Area");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ref");

                    b.HasIndex("Area");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("NovaPoshtaParalle.Entities.City", b =>
                {
                    b.HasOne("NovaPoshtaParalle.Entities.Area", "AreaObj")
                        .WithMany()
                        .HasForeignKey("Area")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaObj");
                });
#pragma warning restore 612, 618
        }
    }
}
