// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaPoshtaParalle;

#nullable disable

namespace NovaPoshtaParalle.Migrations
{
    [DbContext(typeof(MyApplicationContext))]
    [Migration("20250417200837_Add_AreasTabels")]
    partial class Add_AreasTabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("NovaPoshtaParalle.Entities.Area", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ref");

                    b.ToTable("tblAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
